# instructions
bread_bag.open()
slice_1, slice_2 = bread_bag.take_out(2)
pb_jar.open()
jelly_jar.open()
knife.insert(pb_jar)
knife.scoop()
knife.remove()
knife.spread(slice_1)
knife.insert(jelly_jar)
knife.scoop()
knife.remove()
knife.spread(slice_2)
sandwich = assemble(slice_1, slice_2)
bread_bag.close()
pb_jar.close()
jelly_jar.close()
